# Site settings
title:       Anindya Chakravarti
email:       anindyachakravarti@gmail.com
author:      Anindya Chakravarti
description: "Anindya's niche on the Internet"
baseurl:     ""
url:         ""

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: anindya
twitter_username: anindya_1995
google_plus_id: 
linkedin_username: anindyachakravarti

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
paginate_path: "page:num/"
gems: [jekyll-paginate]